# Task type
task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

# Number of classes (fire and smoke)
num_classes: 2
remap_mscoco_category: False


# Training dataloader
train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: ./dataset/FASDD_CV/images/
    ann_file: ./dataset/FASDD_CV/annotations/COCO_CV/Annotations/train.json
    transforms:
      type: Compose
      ops: 
        - {type: RandomPhotometricDistort, p: 0.5}
        - {type: RandomZoomOut, fill: 0}
        - {type: RandomIoUCrop, p: 0.8}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: RandomHorizontalFlip}
        - {type: Resize, size: [640, 640], }
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}   
        - {type: ConvertBoxes, fmt: 'cxcywh', normalize: True}
      policy:
        name: stop_epoch
        epoch: 31 # epoch in [71, ~) stop `ops`
        ops: ['RandomPhotometricDistort', 'RandomZoomOut', 'RandomIoUCrop']
  shuffle: True
  batch_size: 32
  num_workers: 4
  drop_last: True
  collate_fn:
    type: BatchImageCollateFuncion

# Validation dataloader
val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: ./dataset/FASDD_CV/images/
    ann_file: ./dataset/FASDD_CV/annotations/COCO_CV/Annotations/val.json
    transforms:
      type: Compose
      ops: 
        - {type: Resize, size: [640, 640]}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}   
  shuffle: False
  batch_size: 32
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFuncion